CREATE DATABASE Optus;

CREATE TABLE Album(
	
	IdAlbum INT PRIMARY KEY IDENTITY NOT NULL ,
	Nome VARCHAR(20) NOT NULL
	
);

CREATE TABLE Estilo(
	
	IdEstilo INT PRIMARY KEY IDENTITY NOT NULL,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	NomeEstilo VARCHAR(20) NOT NULL 
	
);

CREATE TABLE Artista (
	
	IdArtista INT PRIMARY KEY IDENTITY NOT NULL ,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	NomeArtista VARCHAR(20) NOT NULL 
	
);

CREATE TABLE Usuario(
	
	IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(20) NOT NULL,
	Senha VARCHAR(20) NOT NULL,
	AdminBool BINARY NOT NULL
	
);

CREATE TABLE Acessos(
	
	IdAcesso INT PRIMARY KEY IDENTITY NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum)

);